### ISSUE TITLE
Tradfri Personal experiences

### ISSUE THREAD

**Issue by alex3305** [alex3305/hass-components-debug#3]
## Tracking and discussing personal experiences

Please use this 'issue' to report about experiences with my custom components. When you think you've hit an issue, please report it as a separate issue instead of posting it here.

### New issues

Before posting issues, please try and include the following:

 * Setup and Home Assistant version
 * Commit hash you are running
 * The Home Assistant logging
 * The relevant stack trace (from docker logs / full Home Assistant log
 * How long you were running before hitting the issue
 * Steps to reproduce the issue

> **11-dec** Added #5 if you want to test without unnecessary debug logging.

**Comment by alex3305** [comment]
I'm currently running my latest commit 43e9d004fe270e0422491d48b209e3b008eea56e for about 4 days now and it only hit the observation reset once, this afternoon. So great going for me currently. 

My setup is a Raspberry Pi 3+ with manual HASS.io install on HomeAssistant 0.83.2

cc @morberg

**Comment by EA5JXP** [comment]
Hi!

I have been using your scripts for a few days without problems. After updated home assistant to 0.84.1 it stops working! So I have downgraded to 0.83.3 again.

**Comment by alex3305** [comment]
@droneando I've just updated to 0.84.1 and the component is loaded, and it appears to be working. My version was stable for almost 6 days straight, before I just updated.

**Comment by EA5JXP** [comment]
I discovered there is something wrong with light.mqtt in 0.84x Home Assistant versions, wich is the entity I use for controling my Tradfry lights. There is nothing wrong with your scripts! Thank you
